name: focus
description: "Focus is a deep working focus sessions manager app"
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0

  # Dependency Injection
  get_it: ^9.2.0

  # Database - drift_flutter includes everything
  drift_flutter: ^0.2.8
  drift: ^2.31.0

  # Required native sqlite binaries for Drift on some platforms
  sqlite3_flutter_libs: ^0.5.41

  # UI
  forui: ^0.17.0

  # Audio
  audioplayers: ^6.5.1

  # Notifications
  flutter_local_notifications: ^20.0.0

  # Utils
  intl: ^0.20.2
  uuid: ^4.5.2
  forui_assets: ^0.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.11.0
  drift_dev: ^2.31.0
  riverpod_generator: ^4.0.0+1

flutter:
  uses-material-design: true
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-VariableFont.ttf
          weight: 400