name: focus
description: "Focus is a deep working focus sessions manager app"
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0

  # Dependency Injection
  get_it: ^9.2.0
  injectable: ^2.7.1+4

  # Database
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  path_provider: ^2.1.5

  # UI
  forui: ^0.17.0

  # Audio
  audioplayers: ^6.5.1

  # Notifications
  flutter_local_notifications: ^20.0.0

  # Utils
  intl: ^0.20.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.7.1
  isar_community_generator: ^3.3.0
  riverpod_generator: ^4.0.0+1
  injectable_generator: ^2.6.1